Roman/dw 404/dev guides need update
Arrow-air/website pull request #72
Opened 2022-10-10 20:14 UTC by romanmandryk

2022-10-10 20:41 UTC, owlot requested changes

2022-10-10 20:41 UTC, owlot commented on docs/contributing/guides/style-guides/rust.md
We also have the markdown link check that runs during pre-commit.
The exact make targets that run during the test are:

- rust-test-all (combined target: rust-build rust-check rust-test rust-clippy rust-fmt)
- cspell-test
- toml-test
- python-test
- md-test-links
- editorconfig-test

2022-10-10 21:20 UTC, owlot commented on docs/contributing/guides/style-guides/rust.md
Yeah, I think it makes sense to list them all since all these checks will be running for the Rust projects

2022-10-11 18:55 UTC, ServiceDog approved these changes

2022-10-11 19:11 UTC, owlot approved these changes

2022-10-11 19:12 UTC, merged